'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TsinghuaNet.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 有线IPv4 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Auth4() As String
            Get
                Return ResourceManager.GetString("Auth4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 有线IPv6 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Auth6() As String
            Get
                Return ResourceManager.GetString("Auth6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 登录 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Connect() As String
            Get
                Return ResourceManager.GetString("Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在登录 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Connecting() As String
            Get
                Return ResourceManager.GetString("Connecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 登录错误 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ConnectionFailed() As String
            Get
                Return ResourceManager.GetString("ConnectionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 登录错误：{0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ConnectionFailedWithResult() As String
            Get
                Return ResourceManager.GetString("ConnectionFailedWithResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 未登录 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Disconnected() As String
            Get
                Return ResourceManager.GetString("Disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在注销 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LoggingOut() As String
            Get
                Return ResourceManager.GetString("LoggingOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 注销 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LogOut() As String
            Get
                Return ResourceManager.GetString("LogOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 注销错误 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LogOutFailed() As String
            Get
                Return ResourceManager.GetString("LogOutFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 注销错误：{0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LogOutFailedWithResult() As String
            Get
                Return ResourceManager.GetString("LogOutFailedWithResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 无线 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Net() As String
            Get
                Return ResourceManager.GetString("Net", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 网络异常 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoNetwork() As String
            Get
                Return ResourceManager.GetString("NoNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打开客户端 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NotifyText() As String
            Get
                Return ResourceManager.GetString("NotifyText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 密码： 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PasswordWithColon() As String
            Get
                Return ResourceManager.GetString("PasswordWithColon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 刷新 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Refresh() As String
            Get
                Return ResourceManager.GetString("Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 清华大学校园网登录 的本地化字符串。
        '''</summary>
        Public ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用户名： 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UsernameWithColon() As String
            Get
                Return ResourceManager.GetString("UsernameWithColon", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
